# Generated by Django 4.1.7 on 2023-04-12 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KVM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fqdn", models.CharField(help_text="url", max_length=40, unique=True)),
                ("short_name", models.CharField(help_text="system_name", max_length=8)),
                ("ip", models.GenericIPAddressField(protocol="IPv4")),
                ("number_of_ports", models.PositiveSmallIntegerField(default=32)),
            ],
            options={
                "db_table": "KVM",
            },
        ),
        migrations.CreateModel(
            name="ServerRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("num_rows", models.PositiveSmallIntegerField(default=4)),
                ("num_racks", models.PositiveSmallIntegerField(default=14)),
                ("ports_per_rack", models.PositiveSmallIntegerField(default=2)),
                (
                    "kvm_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="kvm_id",
                        help_text="id_hosts",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kvmwebapp.kvm",
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "ServerRoom",
            },
        ),
        migrations.CreateModel(
            name="KVM_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="username", max_length=40, unique=True),
                ),
                ("password", models.CharField(help_text="password", max_length=255)),
                ("start_time", models.DateTimeField(blank=True)),
                (
                    "first_name",
                    models.CharField(blank=True, help_text="first_name", max_length=40),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, help_text="last_name", max_length=40),
                ),
                (
                    "email",
                    models.EmailField(blank=True, help_text="email", max_length=40),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "KVM_user",
            },
        ),
        migrations.AddField(
            model_name="kvm",
            name="server_room_id",
            field=models.OneToOneField(
                blank=True,
                db_column="server_room_id",
                help_text="server_room_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kvmwebapp.serverroom",
            ),
        ),
        migrations.CreateModel(
            name="Cross",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveSmallIntegerField(help_text="row")),
                ("rack", models.PositiveSmallIntegerField(help_text="rack")),
                ("rack_port", models.PositiveSmallIntegerField(help_text="rack_port")),
                ("rack_port_active", models.BooleanField(default=True)),
                (
                    "kvm_port",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="kvm_port", null=True
                    ),
                ),
                ("kvm_port_active", models.BooleanField(default=False)),
                (
                    "kvm_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="kvm_id",
                        help_text="id_hosts",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kvmwebapp.kvm",
                    ),
                ),
                (
                    "server_room",
                    models.ForeignKey(
                        db_column="server_room",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kvmwebapp.serverroom",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kvmwebapp.kvm_user",
                    ),
                ),
            ],
            options={
                "db_table": "Cross",
                "unique_together": {
                    ("row", "rack", "rack_port", "kvm_port", "server_room")
                },
            },
        ),
    ]
