# Generated by Django 4.1.7 on 2023-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvmwebapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cross",
            name="kvm_port_active",
            field=models.BooleanField(default=False),
        ),
    ]
