# Generated by Django 4.1.7 on 2023-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvmwebapp", "0002_cross_kvm_port_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cross",
            name="kvm_port",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="kvm_port", null=True, unique=True
            ),
        ),
    ]
