# Generated by Django 4.1.7 on 2023-03-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kvmwebapp", "0003_alter_cross_kvm_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cross",
            name="kvm_id",
            field=models.ForeignKey(
                blank=True,
                db_column="kvm_id",
                help_text="id_hosts",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kvmwebapp.kvm",
            ),
        ),
        migrations.AlterField(
            model_name="kvm",
            name="number_of_ports",
            field=models.PositiveSmallIntegerField(default=32),
        ),
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
