# Generated by Django 4.1.7 on 2023-03-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kvmwebapp", "0004_alter_cross_kvm_id_alter_kvm_number_of_ports_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cross",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kvmwebapp.user",
            ),
        ),
    ]
