# Generated by Django 4.1.7 on 2023-03-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvmwebapp", "0005_cross_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(help_text="password", max_length=40),
        ),
        migrations.AlterField(
            model_name="user",
            name="stop_time",
            field=models.DateTimeField(blank=True, help_text="stop_time", null=True),
        ),
    ]
