# Generated by Django 4.1.7 on 2023-03-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvmwebapp", "0006_alter_user_password_alter_user_stop_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kvm",
            name="short_name",
            field=models.CharField(help_text="system_name", max_length=8),
        ),
    ]
